{
 "title": "Performance Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Order CREATION",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "order_created_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Order processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(order_processing_seconds_bucket[5m])) by (le))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "order created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "increase(order_created_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}